DROP DATABASE IF EXISTS dietary_requirements_db;

CREATE DATABASE dietary_requirements_db;

\c dietary_requirements_db;

DROP TABLE IF EXISTS dishes;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS restaurants;

CREATE TABLE users(
   id              SERIAL PRIMARY KEY 
  ,username VARCHAR(14) NOT NULL
  ,password             VARCHAR(62) NOT NULL
  ,first_name         VARCHAR(58) NOT NULL
  ,last_name         VARCHAR(58) NOT NULL
  ,email         VARCHAR(58) NOT NULL
  ,is_admin   BOOLEAN  
);

CREATE TABLE dishes(
   id                        INTEGER  NOT NULL PRIMARY KEY 
  ,dish_name                 VARCHAR(47) NOT NULL
  ,type                      VARCHAR(7) NOT NULL
  ,description               VARCHAR(269)
  ,img                       VARCHAR(30)
  ,price                     VARCHAR(6) NOT NULL
  ,kcal                      INTEGER 
  ,tag                       VARCHAR(45)
  ,spicy                     INTEGER 
  ,contains                  VARCHAR(9)
  ,Dietrary_Requirments_GF   BOOLEAN  NOT NULL
  ,Dietrary_Requirments_VG   BOOLEAN  NOT NULL
  ,Dietrary_Requirments_V    BOOLEAN  NOT NULL
  ,restaurantId              INTEGER  NOT NULL
);

CREATE TABLE restaurants(
   id              INTEGER  NOT NULL PRIMARY KEY 
  ,restaurant_name VARCHAR(14) NOT NULL
  ,url             VARCHAR(62) NOT NULL
  ,address         VARCHAR(58) NOT NULL
);

INSERT INTO users (username, password, first_name, last_name, email, is_admin)
VALUES ('bournejj91',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'jack',
        'bourne',
        'saigonjj91@gmail.com',
        true
);

       


INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (1,'prawn crackers','sharing','Spicy and hard to stop eating! Good to have while your food is being cooked.',NULL,'£3.25',221,NULL,NULL,'prawns',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (2,'Hawker-Style Moo Ping','starter','Garlic and coriander marinated pork skewers seared over charcoal for that juicy, chargrilled texture of bbq street food. Enjoy with spicy tamarind sauce - without being jostled by the night market crowds!',NULL,'£5.95',366,NULL,NULL,'pork',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (3,'Phuket Mussels','starter','A generous bowl of mussels in a rich, red curry broth, garnished with Thai shallots, sliced lime leaves and sweet basil. Add roti or use the shells to mop up the delicious sauce.',NULL,'£6.95',404,NULL,1,'mussels',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (4,'Thai Salmon Nests','starter','Four stacks of salmon, lemongrass, lime cubes (skin on!), ginger, chilli and shredded coconut, drizzled with salty-sweet dressing. Wrap each with a betel leaf and devour!',NULL,'£6.95',381,'Favourite',1,'salmon',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (5,'Sweet Jicama Salad','starter','A salad with big flavours. Jicama (a crunchy, sweet type of potato), juicy star fruit, roasted coconut and crispy tofu croutons with fresh mint and coriander in a delicately sweet sauce.',NULL,'£5.95',228,NULL,NULL,NULL,true,true,true,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (6,'Samui Zingy Prawns','starter','Zingy, citrusy and fresh is how we describe the sauce drizzled on the prawns.',NULL,'£6.95',146,NULL,2,'prawns',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (7,'Grilled Squid & Thai Garlic','starter','Turmeric-grilled squid sprinkled with crunchy fried Thai garlic cloves, skin on. Inspired by a visit to a Rayong beach market with my 3 kids!',NULL,'£6.50',422,NULL,NULL,'squid',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (8,'Mah Kwan Pepper Pork Belly','starter','Mah Kwan is a rare pepper growing wild in Northern Thailand - the secret ingredient in our sweet, sticky pork belly.',NULL,'£6.50',935,NULL,NULL,'pork',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (9,'Som Tam Papaya Salad','starter','Green papaya is white (despite the name!) with a satisfying crunch – we add fresh chilli, cherry tomatoes, dried shrimp, Thai garlic and fish sauce to the clay mortar for a simple but vibrant flavour.',NULL,'£6.50',214,NULL,2,'shrimp',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (10,'Big Flavour Mushroom Larb','starter','A fresh dish of exotic mushrooms in a spicy larb sauce of fresh mint, chilli flakes, ground toasted rice and shallots. Served chilled.',NULL,'£5.95',85,NULL,2,'mushrooms',true,true,true,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (11,'Soft Shell Pranee Prawns','main','Sweet, soft shell prawns coated in Thai herbs and garlic with a little chilli kick. Served with fresh jicama and mint salad with sweet vinegary A-jard sauce.',NULL,'£14.50',1072,NULL,1,'prawns',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (12,'Hake Feast Bowl','main','Generous portions of hake steeped in Thai spices with a hint of sweetness and chilli and the crisp fresh contrast of coconut tips and sweetheart cabbage.',NULL,'£13.95',679,NULL,NULL,'hake',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (13,'Turmeric Sea Bass Parcel','main','Sea bass cooked to perfection in banana leaf with the savoury, robust flavours of turmeric and Thai spices. Served with a stir fry of broccoli, sweetheart cabbage and Thai shallots.',NULL,'£14.95',807,NULL,1,'sea bass',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (14,'Salmon Paneang','main','Salmon fillet in a creamy, red curry sauce with stir fried tenderstem broccoli and pak choi.',NULL,'£14.75',1022,'favourite',1,'salmon',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (15,'Giant Butterfly King Prawn Pad Thai','main','Pad Thai with very big prawns in it! For when you deserve a little something extra.',NULL,'£14.75',1211,NULL,NULL,'prawns',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (16,'Crying Beef','main','Marinated sirloin, grilled Thai-style with charred edges and running juices. Served with a stir-fry of fine beans, red onion and chilli slices.',NULL,'£16.50',628,NULL,1,'beef',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (17,'Chilli & Basil Gra Pao','main','One of the most popular Thai street dishes!',NULL,'£10.50',164,NULL,2,'chicken',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (19,'Chilli & Basil Gra Pao','main','One of the most popular Thai street dishes!',NULL,'£11.95',192,NULL,2,'prawn',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (20,'Chilli & Basil Gra Pao','main','One of the most popular Thai street dishes!',NULL,'£9.50',140,NULL,2,'vegetable',true,true,true,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (21,'Wholesome Cashew Stir Fry','main','Brimming with delicious ingredients - roasted cashew nuts, mushrooms, peppers, onions and chilli.',NULL,'£10.50',580,NULL,1,'chicken',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (22,'Wholesome Cashew Stir Fry','main','Brimming with delicious ingredients - roasted cashew nuts, mushrooms, peppers, onions and chilli.',NULL,'£11.50',627,NULL,1,'beef',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (23,'Wholesome Cashew Stir Fry','main','Brimming with delicious ingredients - roasted cashew nuts, mushrooms, peppers, onions and chilli.',NULL,'£11.95',609,NULL,1,'prawn',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (24,'Wholesome Cashew Stir Fry','main','Brimming with delicious ingredients - roasted cashew nuts, mushrooms, peppers, onions and chilli.',NULL,'£9.50',542,NULL,1,'vegetable',true,true,true,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (25,'Pad Cha','main','A popular seafood stir-fry. The flavour comes from pounded chilli, garlic, finely sliced krachai (like ginger) and fresh peppercorns thrown in a flaming wok.',NULL,'£12.95',517,NULL,2,'seafood',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (26,'Spicy & Tasty Chicken','main','Stir fry chicken breast strips with galangal, lemongrass, lime leaves, garlic and krachai (like ginger). Fiery and flavoursome.',NULL,'£12.95',518,NULL,2,'chicken',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (27,'Thai Red Curry','main','One of the most famous Thai curries! Lovely aromatic sauce made with coconut milk.',NULL,'£10.95',693,NULL,1,'chicken',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (28,'Thai Red Curry','main','One of the most famous Thai curries! Lovely aromatic sauce made with coconut milk.',NULL,'£11.95',731,NULL,1,'beef',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (29,'Thai Red Curry','main','One of the most famous Thai curries! Lovely aromatic sauce made with coconut milk.',NULL,'£11.99',692,NULL,1,'prawn',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (30,'Thai Red Curry','main','One of the most famous Thai curries! Lovely aromatic sauce made with coconut milk.',NULL,'£9.99',766,NULL,1,'vegetable',true,true,true,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (31,'Massaman','main','A curry with mythical origins…but all we care about is its legendary flavour! Simmered in coconut milk and perfumed with cardamom, cinnamon and star anise.',NULL,'£10.99',865,NULL,NULL,'chicken',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (32,'Massaman','main','A curry with mythical origins…but all we care about is its legendary flavour! Simmered in coconut milk and perfumed with cardamom, cinnamon and star anise.',NULL,'£11.75',903,NULL,NULL,'beef',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (33,'Massaman','main','A curry with mythical origins…but all we care about is its legendary flavour! Simmered in coconut milk and perfumed with cardamom, cinnamon and star anise.',NULL,'£11.99',864,NULL,NULL,'prawn',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (34,'Massaman','main','A curry with mythical origins…but all we care about is its legendary flavour! Simmered in coconut milk and perfumed with cardamom, cinnamon and star anise.',NULL,'£9.99',940,NULL,NULL,'vegetable',true,true,true,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (35,'Paneang','main','Paneang is another form of red curry. Thickened with coconut milk and fragranced by finely sliced lime leaves.',NULL,'£10.99',608,NULL,1,'chicken',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (36,'Paneang','main','Paneang is another form of red curry. Thickened with coconut milk and fragranced by finely sliced lime leaves.',NULL,'£11.75',661,NULL,1,'beef',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (37,'Paneang','main','Paneang is another form of red curry. Thickened with coconut milk and fragranced by finely sliced lime leaves.',NULL,'£11.99',576,NULL,1,'prawn',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (37,'Paneang','main','Paneang is another form of red curry. Thickened with coconut milk and fragranced by finely sliced lime leaves.',NULL,'£9.99',662,NULL,1,'vegetable',true,true,true,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (38,'Thai Green Curry','main','Old favourite of “farang” (foreigner) travelling in Thailand. Combination of delicious Thai flavours blended with silky coconut milk.',NULL,'£10.99',680,NULL,NULL,'chicken',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (39,'Thai Green Curry','main','Old favourite of “farang” (foreigner) travelling in Thailand. Combination of delicious Thai flavours blended with silky coconut milk.',NULL,'£11.75',718,NULL,NULL,'beef',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (40,'Thai Green Curry','main','Old favourite of “farang” (foreigner) travelling in Thailand. Combination of delicious Thai flavours blended with silky coconut milk.',NULL,'£11.99',679,NULL,1,'prawn',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (41,'Thai Green Curry','main','Old favourite of “farang” (foreigner) travelling in Thailand. Combination of delicious Thai flavours blended with silky coconut milk.',NULL,'£9.99',753,NULL,1,'vegetable',true,true,true,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (42,'Rising Star Red Duck Curry','main','Our famous curry has had a make-over using duck breast and adding juicy star fruits and pea aubergines.',NULL,'£15.75',730,'favourite',NULL,'duck',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (43,'Giggling Pad Thai','main','Flavoursome rice noodles with tofu, beansprouts, sliced red onions, Thai chives and crunchy peanuts.',NULL,'£8.99',1123,NULL,NULL,'chicken',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (44,'Giggling Pad Thai','main','Flavoursome rice noodles with tofu, beansprouts, sliced red onions, Thai chives and crunchy peanuts.',NULL,'£9.99',1132,NULL,NULL,'prawn',true,false,false,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (45,'Giggling Pad Thai','main','Flavoursome rice noodles with tofu, beansprouts, sliced red onions, Thai chives and crunchy peanuts.',NULL,'£7.99',1082,NULL,NULL,'vegetable',true,false,true,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (46,'Stir Fry Noodle with Beansprouts','main','Simple and satisfying - noodles stir fried in house sauce with beansprouts and spring onions.',NULL,'£6.50',490,NULL,NULL,'vegetable',true,true,true,1);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (47,'Chorizo Hash','brunch','with fried potatoes, roasted kale, spring greens, roasted cherry tomatoes, fried red onion and spicy pepper sauce, topped with a fried egg',NULL,'£9.50',851,NULL,NULL,'chorizo',true,false,false,2);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (48,'Mexican Superbowl with Chorizo','main','Black beans, edamame guacamole, roasted sweet potato with pomegranate molasses, spicy rice, wild rocket and chipotle tomato salsa',NULL,'£12.20',828,NULL,NULL,'chorizo',true,false,false,2);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (49,'Pulled Brisket Chilli','main','Slow-cooked beef brisket, black beans and mature cheddar served with spicy rice, spring onion, red chilli and yoghurt',NULL,'£11.50',821,NULL,1,'beef',true,false,false,2);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (50,'Pulled Brisket Chilli with Chorizo','main','Slow-cooked beef brisket, black beans and mature cheddar served with spicy rice, spring onion, red chilli and yoghurt',NULL,'£13.25',970,NULL,1,'chorizo',true,false,false,2);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (51,'Mexican Superbowl with Halloumi','main','Black beans, edamame guacamole, roasted sweet potato with grilled halloumi, pomegranate molasses, spicy rice, wild rocket and chipotle tomato salsa',NULL,'£12.20',840,NULL,NULL,'halloumi',true,false,true,2);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (52,'GF Buttermilk Fried Chicken with Chipotle Mayo','main','Lightly spiced crumbed chicken breast served with chipotle mayo, house slaw and fries',NULL,'£10.95',1038,NULL,NULL,'chicken',true,false,false,2);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (53,'GF Wan Chai Fried Rice Bowl with Miso Aubergine','main','Fried rice in mushroom XO sauce with spring onions and greens, topped with edamame beans, pickled slaw, roasted kale, miso aubergine, fried egg and chilli flakes',NULL,'£11.75',711,NULL,1,'vegetable',true,false,true,2);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (54,'Vegan Roasted Aubergine Massaman Curry','main','with crispy chickpeas and roasted sweet potato, served with lime & coriander rice',NULL,'£10.25',681,NULL,NULL,'vegetable',true,true,true,2);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (55,'Vegan Beyond Cheese Burger','main','Plant-based burger patty from Beyond Meat, with lettuce, tomato, pickled red onion, vegan smoked gouda cheese and vegan chipotle mayo in a brioche style bun, with vegan house slaw & fries or salad',NULL,'£12.95',868,NULL,NULL,'vegetable',false,true,true,2);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (56,'Vegan Sweet Potatoes & Falafel Salad','main','Plant-based burger patty from Beyond Meat, with lettuce, tomato, pickled red onion, vegan smoked gouda cheese and vegan chipotle mayo in a brioche style bun, with vegan house slaw & fries or salad',NULL,'£10.95',757,NULL,NULL,'vegetable',true,true,true,2);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (57,'Casa Houmous & Flatbread','starter','Smoked paprika & sumac houmous with parsley, chickpeas & pomegranate.',NULL,'£6.75',NULL,NULL,NULL,'houmous',true,true,true,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (58,'Honey & Mustard Sausages','starter','Pork sausages roasted with wholegrain mustard & honey.',NULL,'£7.00',NULL,NULL,NULL,'pork',true,false,false,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (59,'Imam Bayildi & Flatbread','starter','Smokey aubergine, tomato & pepper dip with toasted flatbread.',NULL,'£7.75',NULL,NULL,NULL,'vegetable',true,true,true,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (59,'Chorizo in Red Wine','starter','Premium slightly spicy chorizo slow-cooked in red wine with shallots & bay leaves.',NULL,'£8.00',NULL,NULL,NULL,'chorizo',true,false,false,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (60,'Padron Peppers','starter','Spanish green peppers flash fried in olive oil with a generous sprinkling of sea salt.',NULL,'£7.00',NULL,NULL,NULL,'vegetable',true,true,true,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (61,'Garlic King Prawns with Bread','starter','Freshly cooked king prawns with lots of garlic juices for dipping.',NULL,'£9.00',NULL,NULL,NULL,'prawns',true,false,false,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (62,'Smoked Salmon Tortelloni','main','Fresh pasta stuffed with smoked salmon & served with lemon & dill butter.',NULL,'£8.00',NULL,NULL,NULL,'salmon',false,false,false,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (63,'Pork Belly with Moroccan Potatoes','main','Pork belly from Suffolk reared pigs at Dingley Dell farm, Moroccan potatoes, date tamarind & apple sauce plus crispy serrano ham.',NULL,'£9.50',NULL,NULL,NULL,'salmon',true,false,false,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (64,'Smoked Tofu with Moroccan Potatoes','main','Smoked tofu, Moroccan potatoes, date tamarind & apple sauce plus crispy parsnip.',NULL,'£9.00',NULL,NULL,NULL,'tofu',false,true,true,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (65,'Lamb Koftas with Tzatziki','main','Spiced Persian meatballs with pinenuts, served with homemade fresh dill dip.',NULL,'£8.75',NULL,NULL,NULL,'lamb',true,false,false,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (66,'Spanish Meatballs','main','Traditional albondigas recipe is homemade with pork & beef.',NULL,'£8.00',NULL,NULL,NULL,'pork',true,false,false,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (67,'Halloumi with Shakshuka','main','Griddled Cypriot goat''s cheese with middle Eastern spiced tomatoes, peppers & onions.',NULL,'£8.50',NULL,NULL,NULL,'halloumi',true,false,true,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (68,'Falafel with Muhumarra & Hummous','main','Chickpea based fritters with fresh herbs served with spiced red pepper dip & houmous',NULL,'£8.25',NULL,NULL,NULL,'falafel',false,true,true,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (69,'Vegetable Tagine with Rice','main','Aromatic Moroccan vegetable stew with basmati rice.',NULL,'£8.00',NULL,NULL,NULL,'vegetable',true,true,true,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (70,'Patatas Bravas','main','Deep-fried crispy potatoes with a spicy tomato sauce.',NULL,'£6.50',NULL,NULL,NULL,'vegetable',true,true,true,3);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (71,'PEA & OLIVE TARTLET','starter','Olive tapenade, tomatoes, roasted pine nuts, rocket',NULL,'£6.95',298,NULL,NULL,'vegetable',false,true,true,4);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (72,'BEET TARTARE','starter','Marinated red beetroot, mustard vinaigrette, yoghurt dressing, basil oil, toasted baguette',NULL,'£6.50',359,NULL,NULL,'vegetable',true,true,true,4);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (73,'CELERIAC FRICASSÉE','main','Salt-baked celeriac, haricot blanc purée, grapes, mixed seed & mushroom granola (contains nuts), pickled shallots, charred baby gem, basil oil',NULL,'£13.25',757,NULL,NULL,'vegetable',true,true,true,4);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (74,'SQUASH TABOULÉ','main','Inspired by Marseille’s North African quarter. Roasted butternut squash & courgette, giant harissa couscous, chickpeas, spinach, rocket, coconut yoghurt',NULL,'£12.95',777,NULL,NULL,'vegetable',false,true,true,4);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (75,'VEGAN CÔTE BURGER','main','Moving Mountains™ burger patty, vegan cheese, truffle mayonnaise, caramelised red onion, brioche bun, frites',NULL,'£13.95',1297,NULL,NULL,'vegetable',false,true,true,4);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (76,'Halloumi Fries','starter','Served with a tomato & sweet chilli dip',NULL,'£7.25',NULL,NULL,NULL,'halloumi',true,false,true,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (76,'Vegan Chilli Nachos','starter','Served with our homemade vegan chilli, vegan cheese, salsa, guacamole, spring onions and red chillie',NULL,'£8.50',NULL,NULL,NULL,'vegetable',false,true,true,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (77,'Red Pepper Houmous','starter','Houmous served with olive oil, slow roasted mixed peppers, paprika and served with sliced, toasted pitta bread',NULL,'£6.50',NULL,NULL,NULL,'vegetable',false,true,true,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (78,'Poutine','starter','In a nutshell it''s rosemary salted fries covered in our amazing gravy and cheese',NULL,'£8.50',NULL,NULL,NULL,'vegetable',true,false,false,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (79,'St John''s','main','Seasoned beef patty, burger relish, applewood smoked cheddar dry cured smoked streaky bacon',NULL,'£14.50',NULL,NULL,NULL,'beef',true,false,false,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (80,'BBQ Chicken','main','Grilled chicken breast fillet, topped with cheddar cheese, streaky bacon and smothered in BBQ sauce',NULL,'£14.50',NULL,NULL,NULL,'chicken',true,false,false,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (81,'BBQ Chicken','main','Grilled chicken breast fillet, topped with cheddar cheese, streaky bacon and smothered in BBQ sauce',NULL,'£14.50',NULL,NULL,NULL,'chicken',true,false,false,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (81,'BBQ Pulled Pork','main','Seasoned beef patty, burger relish, applewood smoked cheddar and topped with our homemade BBQ pulled pork',NULL,'£14.50',NULL,NULL,NULL,'pork',true,false,false,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (82,'BBQ Pulled Pork','main','Seasoned beef patty, burger relish, applewood smoked cheddar and topped with our homemade BBQ pulled pork',NULL,'£14.50',NULL,NULL,NULL,'pork',true,false,false,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (83,'Lamb Kofta','main','Grilled spiced minced lamb burger, spiced red cabbage and Tavern spicy mayo',NULL,'£14.95',NULL,NULL,NULL,'lamb',true,false,false,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (84,'Moving Mountains Burger','main','Plant based burger patty, vegan burger sauce, smoky cheese and house slawo',NULL,'£13.50',NULL,NULL,NULL,'vegetable',true,true,true,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (85,'Loaded Vegan Pizza','main','Marinara tomato sauce, smoky cheese, red onion, roasted red peppers, mushrooms, homemade vegan chilli & jalapenos',NULL,'£11.25',NULL,'extra £1 for gluten free',1,'vegetable',true,true,true,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (86,'Margherita','main','Marinara tomato sauce, mozzarella and basil',NULL,'£10.00',NULL,'extra £1 for gluten free',NULL,'vegetable',true,false,true,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (87,'BUDDHA SALAD BOWL','main','Mixed leaf salad & fresh spinach topped with cous-cous, sliced beetroot, spiced red cabbage, guacamole, mixed olives, mixed beans, shaved cucumber and carrot rolls, mixed peppers topped with omega seed sprinkles and accompanied with a pot of our homemade salad dressing',NULL,'£12.50',NULL,'can be made gluten-free by removing cous-cous',NULL,'falafel',true,true,true,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (88,'BUDDHA SALAD BOWL','main','Mixed leaf salad & fresh spinach topped with cous-cous, sliced beetroot, spiced red cabbage, guacamole, mixed olives, mixed beans, shaved cucumber and carrot rolls, mixed peppers topped with omega seed sprinkles and accompanied with a pot of our homemade salad dressing',NULL,'£12.50',NULL,'can be made gluten-free by removing cous-cous',NULL,'halloumi',true,false,true,5);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (89,'prawn raisukaree','main','mild + citrusy. prawns. coconut. mangetout. peppers. red + spring onion. sesame seeds. chilli. coriander. fresh lime. white rice',NULL,'£13.95',1035,NULL,NULL,'prawn',true,false,false,6);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (90,'chicken raisukaree','main','mild + citrusy. chicken. coconut. mangetout. peppers. red + spring onion. sesame seeds. chilli. coriander. fresh lime. white rice',NULL,'£12.95',1123,NULL,NULL,'chicken',true,false,false,6);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (91,'raisukaree tofu','main','mild + citrusy. chicken. coconut. mangetout. peppers. red + spring onion. sesame seeds. chilli. coriander. fresh lime. white rice',NULL,'£12.95',1123,NULL,NULL,'tofu',true,true,true,6);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (92,'kare burosu ramen','main','shichimi-coated silken tofu. grilled mixed mushrooms. seasonal greens. carrot. chilli. coriander. udon noodle',NULL,'£11.95',594,NULL,NULL,'tofu',false,true,true,6);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (93,'yasai yaki soba','main','thin noodles. mushroom. egg. peppers. beansprouts. white + spring onion. fried shallots. pickled ginger. sesame seeds',NULL,'£9.50',785,NULL,NULL,'vegetable',false,false,true,6);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (94,'yasai yaki soba on udon noodle','main','udon noodles. mushrooms. peppers. beansprouts. white + spring onions. fried shallots. pickled ginger. sesame seeds',NULL,'£9.50',569,NULL,NULL,'vegetable',false,true,true,6);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (95,'shu''s shiok jackfruit','main','turmeric + ginger jackfruit, roasted and served on a bed of coconut + lemongrass dressed rice. pickled slaw + radish. chilli. coriander. caramelised lime',NULL,'£10.50',569,NULL,NULL,'vegetable',false,true,true,6);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (96,'Olives','starter','House mix of green and black olives',NULL,'£3.25',NULL,NULL,NULL,'vegetable',true,true,true,7);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (97,'Garlic Bread with Balsamic Onions & Mozzarella','starter',NULL,NULL,'£7.50',NULL,NULL,NULL,'vegetable',true,false,true,7);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (98,'Meatballs','starter',NULL,NULL,'£7.25',NULL,NULL,NULL,'vegetable',true,false,false,7);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (99,'Italian Hummus','starter','Our creamy cannellini bean dip finished with freshly chopped parsley and lemon oil, served with grilled flatbread',NULL,'£5.95',NULL,NULL,NULL,'vegetable',false,true,true,7);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (100,'King Prawns','starter','With a chilli tomato sauce, served with garlic bread',NULL,'£7.75',NULL,NULL,NULL,'prawn',true,false,false,7);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (101,'Penne Arrabbiata','starter',NULL,NULL,'£9.75',NULL,NULL,NULL,'vegetable',false,true,true,7);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (101,'Penne Arrabbiata','main',NULL,NULL,'£9.75',NULL,'can be gluten-free fusilli',NULL,'vegetable',true,true,true,7);
INSERT INTO dishes(id,dish_name,type,description,img,price,kcal,tag,spicy,contains,Dietrary_Requirments_GF,Dietrary_Requirments_VG,Dietrary_Requirments_V,restaurantId) VALUES (102,'Spaghetti Bolognese','main','Traditional beef Bolognese with spaghetti in a rich tomato and red wine sauce',NULL,'£12.50',NULL,'can be gluten-free fusilli',NULL,'beef',true,false,false,7);

INSERT INTO restaurants(id,restaurant_name,url,address) VALUES (1,'Giggling Squid','https://www.gigglingsquid.com/','21 Abbeygate St, Bury Saint Edmunds IP33 1UN');
INSERT INTO restaurants(id,restaurant_name,url,address) VALUES (2,'Casa','https://www.casabse.co.uk/','98 Risbygate St, Bury Saint Edmunds IP33 3AA');
INSERT INTO restaurants(id,restaurant_name,url,address) VALUES (3,'Edmundo','https://thelounges.co.uk/edmundo/','28 Cornhill, Bury Saint Edmunds IP33 1DY');
INSERT INTO restaurants(id,restaurant_name,url,address) VALUES (4,'Cote','https://www.cote.co.uk/restaurant/bury-st-edmunds/','52 Abbeygate St, Bury Saint Edmunds IP33 1LB');
INSERT INTO restaurants(id,restaurant_name,url,address) VALUES (5,'The Tavern','https://www.tavernbse.co.uk/','88-89 St John''s St, Bury Saint Edmunds IP33 1SQ');
INSERT INTO restaurants(id,restaurant_name,url,address) VALUES (6,'Wagamama','https://www.wagamama.com/','5Arc Shopping Centre, unit 7 the, Bury St Edmunds IP33 3FA');
INSERT INTO restaurants(id,restaurant_name,url,address) VALUES (7,'Prezzo','https://www.prezzorestaurants.co.uk/restaurant/bury-st-edmunds','35-36 Abbeygate St, Bury Saint Edmunds IP33 1LW');

INSERT INTO users(id, username, password, first_name, last_name, email, is_admin) VALUES (1, 'bournejj91', 'blagden91', 'jack', 'bourne', 'cras.jbourne@gmail.com', true )